# Generated by Django 4.0 on 2021-12-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['timestamp']},
        ),
    ]
