# Generated by Django 4.0 on 2021-12-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
