# Generated by Django 4.0 on 2021-12-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_perfil_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
