# Generated by Django 4.0 on 2021-12-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_remove_perfil_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
