# Generated by Django 4.0 on 2021-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_perfil_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
