# Generated by Django 4.0 on 2021-12-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_like_post_alter_like_user'),
        ('Usuarios', '0010_notificacion_remove_notificacionfollow_from_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Posts.comentario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Posts.like'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Posts.post'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
